stages:
  - build
  - publish
  - pages


build:
  stage: build
  image: dotnetimages/microsoft-dotnet-core-sdk-nodejs:7.0_19.x
  script:
    - dotnet restore
    - dotnet build
  artifacts:
    when: on_success
    expire_in: 1 week
    untracked: true

publish:
  stage: publish
  image: dotnetimages/microsoft-dotnet-core-sdk-nodejs:7.0_19.x
  script:
    - dotnet publish -o ./public
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - ./public

pages:
  stage: pages
  image: alpine:latest
  needs: [publish]
  script:
    - cp ./public/wwwroot/* ./public
  artifacts:
    when: on_success
    expire_in: 1 week
    paths:
      - ./public