stages:
  - build
  - deploy


build:
  stage: build
  image: mcr.microsoft.com/dotnet/sdk:latest
  script:
    - dotnet restore
    - dotnet build
  artifacts:
    when: on_success
    expire_in: 1 week
    untracked: true