stages:
  - build
  - deploy


build:
  stage: build
  image: dotnetimages/microsoft-dotnet-core-sdk-nodejs
  script:
    - dotnet restore
    - dotnet build
  artifacts:
    when: on_success
    expire_in: 1 week
    untracked: true